# EMULATORS, DEV USAGE ONLY
# DO NOT USE IN PRODUCTION

services:
  emulators:
    image: andreysenov/firebase-tools:latest-slim
    volumes:
      - ./:/home/node
    ports:
      - "9199:9199"
      - "9099:9099"
      - "9005:9005"
      - "9000:9000"
      - "8085:8085"
      - "8080:8080"
      - "5001:5001"
    entrypoint: ["firebase", "emulators:start", "--project", "sarah-rp-manager"]