create table
  public.messages (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    user_id bigint null,
    message text not null,
    image_url text null,
    constraint messages_pkey primary key (id),
    constraint messages_user_id_fkey foreign key (user_id) references users (id) on delete set null
  ) tablespace pg_default;