create table
  public.roleplays_users (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    roleplay_id bigint not null,
    user_id bigint not null,
    is_admin boolean not null default false,
    constraint roleplays_users_pkey primary key (id),
    constraint roleplays_users_roleplay_id_fkey foreign key (roleplay_id) references roleplays (id) on delete cascade,
    constraint roleplays_users_user_id_fkey foreign key (user_id) references users (id) on delete cascade
  ) tablespace pg_default;