create table
  public.roleplays (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    title text not null,
    description text null,
    message_board text null,
    start_date timestamp without time zone null,
    constraint roleplays_pkey primary key (id)
  ) tablespace pg_default;