create table
  public.roles_users (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    role_id bigint not null,
    user_id bigint not null,
    name text null,
    avatar text null,
    description text null,
    constraint roles_users_pkey primary key (id),
    constraint roles_users_role_id_fkey foreign key (role_id) references roles (id) on delete cascade,
    constraint roles_users_user_id_fkey foreign key (user_id) references users (id)
  ) tablespace pg_default;