create table
  public.roles (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    roleplay_id bigint null,
    name text not null,
    max_users smallint null,
    constraint roles_pkey primary key (id),
    constraint roles_roleplay_id_fkey foreign key (roleplay_id) references roleplays (id) on delete cascade
  ) tablespace pg_default;